openapi: 3.0.1

info:
  version: 1.0.0
  title: 'Web practice API'

servers:
  - url: http://web-practice.local:8080/api
    description: 'Локальный сервер'

paths:
  /auth/sign-in:
    $ref: './paths/auth/sign-in.yml#/paths/auth~1sign-in'
  /auth/sign-up:
    $ref: './paths/auth/sign-up.yml#/paths/auth~1sign-up'
  /auth/verify-email/{user}:
    $ref: './paths/auth/verify-email.yml#/paths/auth~1verify-email~1{user}'
  /auth/user:
    $ref: './paths/auth/user.yml#/paths/auth~1user'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  headers:
    Api-Token:
      description: 'JWT токен'
      schema:
        type: string

security:
  - bearerAuth: []
